### ISSUE TITLE
Look into better data structure than the current vector<vector<string>>

### ISSUE THREAD

**Issue by ghost** [abraker95/Osu-API-Cpp#8]
Suggestion by Soinou (https://osu.ppy.sh/forum/p/4199805)

Something like an Osu::User that will contain all the informations parsed from the json.
For example:

```
namespace Osu
{
    struct User
    {
        long id;
        std::string username;
        ...
    }
}
```

This would be way better to understand and to use than a vector, and would be less prone to errors.

**Comment by abraker95** [comment]
Suggestion by Soinou (https://osu.ppy.sh/forum/p/4199805)

No, I meant that you would make something like an Osu::User that will contain all the informations parsed from the json.
For example:

~~~
namespace Osu
{
    struct User
    {
        long id;
        std::string username;
        ...
    }
}
~~~

This would be way better to understand and to use than a vector, and would be less prone to errors.
